### ISSUE TITLE
A project admin can remove permissions to access their own project

### ISSUE THREAD

**Issue by martin-hajek** [RE-QDA/requal#131]
A project administrator can accidentally lose access to their project if they remove all permissions themselves. This should not be possible because there is no way to restore access.
![permissions](https://github.com/RE-QDA/requal/assets/54745940/f5687217-3000-4d38-8917-9f4a3d5b1541)

**Comment by martin-hajek** [comment]
This is a project by a student who reports that clicking on the padlock icon displays a warning about insufficient permissions. I am also a member of that project and cannot edit permissions. This is an unfortunate situation because all his work in the project is lost for good. Or is there any way to recover it?

**Comment by hlageek** [comment]
It can be recovered by editing permissions directly in the database by sysadmin. But it should not come down to this, I thought I made some precautions so that at least one project member retains editing permissions. But either it was not implemented or there the solution was not foolproof. I will fix this soon.

**Comment by hlageek** [comment]
Ok, the precaution is implemented only for removing project members:
```
if (any(owner_check == 1)) warn_user("Project owners cannot be removed from project.")
```
- [ ] implement owner check for permission removal
